# docker-compose.yml

version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  nestjs:
    build: .
    container_name: nestjs
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: user
      DB_PASSWORD: user_password
      DB_DATABASE: my_database
    depends_on:
      - mysql
    ports:
      - '3001:3001'

volumes:
  mysql-data:
